# Generated by Django 3.1.6 on 2021-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210211_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(max_length=10)),
                ('product_category', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
