# Generated by Django 3.1.6 on 2021-02-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210211_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
